//
//  PokemonGameNames.swift
//  PokemonLeafGreenApp-UIKit
//
//  Created by Ameer Bajwa on 7/14/25.
//

public enum PokemonLocationIdNameConfiguration {
    case palletTown
    case route1
    case virdianCity
    case route22
    case route2
    case virdianForest
    case pewterCity
    
    var id: Int {
        switch self {
        case .palletTown:
            return 1
        case .route1:
            return 2
        case .virdianCity:
            return 3
        case .route22:
            return 4
        case .route2:
            return 5
        case .virdianForest:
            return 6
        case .pewterCity:
            return 7
        }
    }
    
    var name: String {
        switch self {
        case .palletTown:
            return "Pallet Town"
        case .route1:
            return "Route 1"
        case .virdianCity:
            return "Virdian City"
        case .route22:
            return "Route 22"
        case .route2:
            return "Route 2"
        case .virdianForest:
            return "Virdian Forest"
        case .pewterCity:
            return "Pewter City"
        }
    }
}

public enum PokemonIdNameConfiguration {
    case bulbasaur
    case ivysaur
    case venusaur
    case charmander
    case charmeleon
    case charizard
    case squirtle
    case wartortle
    case blastoise
    case caterpie
    case metapod
    case butterfree
    case weedle
    case kakuna
    case beedrill
    case pidgey
    case pidgeotto
    case pidgeot
    case rattata
    case raticate
    case spearow
    case fearow
    case ekans
    case arbok
    case pikachu
    case raichu
    case sandshrew
    case sandslash
    case nidoranf
    case nidorina
    case nidoqueen
    case nidoranm
    case nidorino
    case nidoking
    case clefairy
    case clefable
    case vulpix
    case ninetales
    case jigglypuff
    case wigglytuff
    case zubat
    case golbat
    case oddish
    case gloom
    case vileplume
    case paras
    case parasect
    case venonat
    case venomoth
    case diglett
    case dugtrio
    case meowth
    case persian
    case psyduck
    case golduck
    case mankey
    case primeape
    case growlithe
    case arcanine
    case poliwag
    case poliwhirl
    case poliwrath
    case abra
    case kadabra
    case alakazam
    case machop
    case machoke
    case machamp
    case bellsprout
    case weepinbell
    case victreebel
    case tentacool
    case tentacruel
    case geodude
    case graveler
    case golem
    case ponyta
    case rapidash
    case slowpoke
    case slowbro
    case magnemite
    case magneton
    case farfetchd
    case doduo
    case dodrio
    case seel
    case dewgong
    case grimer
    case muk
    case shellder
    case cloyster
    case gastly
    case haunter
    case gengar
    case onix
    case drowzee
    case hypno
    case krabby
    case kingler
    case voltorb
    case electrode
    case exeggcute
    case exeggutor
    case cubone
    case marowak
    case hitmonlee
    case hitmonchan
    case lickitung
    case koffing
    case weezing
    case rhyhorn
    case rhydon
    case chansey
    case tangela
    case kangaskhan
    case horsea
    case seadra
    case goldeen
    case seaking
    case staryu
    case starmie
    case mrmime
    case scyther
    case jynx
    case electabuzz
    case magmar
    case pinsir
    case tauros
    case magikarp
    case gyarados
    case lapras
    case ditto
    case eevee
    case vaporeon
    case jolteon
    case flareon
    case porygon
    case omanyte
    case omastar
    case kabuto
    case kabutops
    case aerodactyl
    case snorlax
    case articuno
    case zapdos
    case moltres
    case dratini
    case dragonair
    case dragonite
    case mewtwo
    case mew
    
    var name: String {
        switch self {
        case .bulbasaur:
            return "bulbasaur"
        case .ivysaur:
            return "ivysaur"
        case .venusaur:
            return "venusaur"
        case .charmander:
            return "charmander"
        case .charmeleon:
            return "charmeleon"
        case .charizard:
            return "charizard"
        case .squirtle:
            return "squirtle"
        case .wartortle:
            return "wartortle"
        case .blastoise:
            return "blastoise"
        case .caterpie:
            return "caterpie"
        case .metapod:
            return "metapod"
        case .butterfree:
            return "butterfree"
        case .weedle:
            return "weedle"
        case .kakuna:
            return "kakuna"
        case .beedrill:
            return "beedrill"
        case .pidgey:
            return "pidgey"
        case .pidgeotto:
            return "pidgeotto"
        case .pidgeot:
            return "pidgeot"
        case .rattata:
            return "rattata"
        case .raticate:
            return "raticate"
        case .spearow:
            return "spearow"
        case .fearow:
            return "fearow"
        case .ekans:
            return "ekans"
        case .arbok:
            return "arbok"
        case .pikachu:
            return "pikachu"
        case .raichu:
            return "raichu"
        case .sandshrew:
            return "sandshrew"
        case .sandslash:
            return "sandslash"
        case .nidoranf:
            return "nidoran-f"
        case .nidorina:
            return "nidorina"
        case .nidoqueen:
            return "nidoqueen"
        case .nidoranm:
            return "nidoran-m"
        case .nidorino:
            return "nidorino"
        case .nidoking:
            return "nidoking"
        case .clefairy:
            return "clefairy"
        case .clefable:
            return "clefable"
        case .vulpix:
            return "vulpix"
        case .ninetales:
            return "ninetales"
        case .jigglypuff:
            return "jigglypuff"
        case .wigglytuff:
            return "wigglytuff"
        case .zubat:
            return "zubat"
        case .golbat:
            return "golbat"
        case .oddish:
            return "oddish"
        case .gloom:
            return "gloom"
        case .vileplume:
            return "vileplume"
        case .paras:
            return "paras"
        case .parasect:
            return "parasect"
        case .venonat:
            return "venonat"
        case .venomoth:
            return "venomoth"
        case .diglett:
            return "diglett"
        case .dugtrio:
            return "dugtrio"
        case .meowth:
            return "meowth"
        case .persian:
            return "persian"
        case .psyduck:
            return "psyduck"
        case .golduck:
            return "golduck"
        case .mankey:
            return "mankey"
        case .primeape:
            return "primeape"
        case .growlithe:
            return "growlithe"
        case .arcanine:
            return "arcanine"
        case .poliwag:
            return "poliwag"
        case .poliwhirl:
            return "poliwhirl"
        case .poliwrath:
            return "poliwrath"
        case .abra:
            return "abra"
        case .kadabra:
            return "kadabra"
        case .alakazam:
            return "alakazam"
        case .machop:
            return "machop"
        case .machoke:
            return "machoke"
        case .machamp:
            return "machamp"
        case .bellsprout:
            return "bellsprout"
        case .weepinbell:
            return "weepinbell"
        case .victreebel:
            return "victreebel"
        case .tentacool:
            return "tentacool"
        case .tentacruel:
            return "tentacruel"
        case .geodude:
            return "geodude"
        case .graveler:
            return "graveler"
        case .golem:
            return "golem"
        case .ponyta:
            return "ponyta"
        case .rapidash:
            return "rapidash"
        case .slowpoke:
            return "slowpoke"
        case .slowbro:
            return "slowbro"
        case .magnemite:
            return "magnemite"
        case .magneton:
            return "magneton"
        case .farfetchd:
            return "farfetch'd"
        case .doduo:
            return "doduo"
        case .dodrio:
            return "dodrio"
        case .seel:
            return "seel"
        case .dewgong:
            return "dewgong"
        case .grimer:
            return "grimer"
        case .muk:
            return "muk"
        case .shellder:
            return "shellder"
        case .cloyster:
            return "cloyster"
        case .gastly:
            return "gastly"
        case .haunter:
            return "haunter"
        case .gengar:
            return "gengar"
        case .onix:
            return "onix"
        case .drowzee:
            return "drowzee"
        case .hypno:
            return "hypno"
        case .krabby:
            return "krabby"
        case .kingler:
            return "kingler"
        case .voltorb:
            return "voltorb"
        case .electrode:
            return "electrode"
        case .exeggcute:
            return "exeggcute"
        case .exeggutor:
            return "exeggutor"
        case .cubone:
            return "cubone"
        case .marowak:
            return "marowak"
        case .hitmonlee:
            return "hitmonlee"
        case .hitmonchan:
            return "hitmonchan"
        case .lickitung:
            return "lickitung"
        case .koffing:
            return "koffing"
        case .weezing:
            return "weezing"
        case .rhyhorn:
            return "rhyhorn"
        case .rhydon:
            return "rhydon"
        case .chansey:
            return "chansey"
        case .tangela:
            return "tangela"
        case .kangaskhan:
            return "kangaskhan"
        case .horsea:
            return "horsea"
        case .seadra:
            return "seadra"
        case .goldeen:
            return "goldeen"
        case .seaking:
            return "seaking"
        case .staryu:
            return "staryu"
        case .starmie:
            return "starmie"
        case .mrmime:
            return "Mr. Mime"
        case .scyther:
            return "scyther"
        case .jynx:
            return "jynx"
        case .electabuzz:
            return "electabuzz"
        case .magmar:
            return "magmar"
        case .pinsir:
            return "pinsir"
        case .tauros:
            return "tauros"
        case .magikarp:
            return "magikarp"
        case .gyarados:
            return "gyarados"
        case .lapras:
            return "lapras"
        case .ditto:
            return "ditto"
        case .eevee:
            return "eevee"
        case .vaporeon:
            return "vaporeon"
        case .jolteon:
            return "jolteon"
        case .flareon:
            return "flareon"
        case .porygon:
            return "porygon"
        case .omanyte:
            return "omanyte"
        case .omastar:
            return "omastar"
        case .kabuto:
            return "kabuto"
        case .kabutops:
            return "kabutops"
        case .aerodactyl:
            return "aerodactyl"
        case .snorlax:
            return "snorlax"
        case .articuno:
            return "articuno"
        case .zapdos:
            return "zapdos"
        case .moltres:
            return "moltres"
        case .dratini:
            return "dratini"
        case .dragonair:
            return "dragonair"
        case .dragonite:
            return "dragonite"
        case .mewtwo:
            return "mewtwo"
        case .mew:
            return "mew"
        }
    }
    
    var id: Int {
        switch self {
        case .bulbasaur:
            return 1
        case .ivysaur:
            return 2
        case .venusaur:
            return 3
        case .charmander:
            return 4
        case .charmeleon:
            return 5
        case .charizard:
            return 6
        case .squirtle:
            return 7
        case .wartortle:
            return 8
        case .blastoise:
            return 9
        case .caterpie:
            return 10
        case .metapod:
            return 11
        case .butterfree:
            return 12
        case .weedle:
            return 13
        case .kakuna:
            return 14
        case .beedrill:
            return 15
        case .pidgey:
            return 16
        case .pidgeotto:
            return 17
        case .pidgeot:
            return 18
        case .rattata:
            return 19
        case .raticate:
            return 20
        case .spearow:
            return 21
        case .fearow:
            return 22
        case .ekans:
            return 23
        case .arbok:
            return 24
        case .pikachu:
            return 25
        case .raichu:
            return 26
        case .sandshrew:
            return 27
        case .sandslash:
            return 28
        case .nidoranf:
            return 29
        case .nidorina:
            return 30
        case .nidoqueen:
            return 31
        case .nidoranm:
            return 32
        case .nidorino:
            return 33
        case .nidoking:
            return 34
        case .clefairy:
            return 35
        case .clefable:
            return 36
        case .vulpix:
            return 37
        case .ninetales:
            return 38
        case .jigglypuff:
            return 39
        case .wigglytuff:
            return 40
        case .zubat:
            return 41
        case .golbat:
            return 42
        case .oddish:
            return 43
        case .gloom:
            return 44
        case .vileplume:
            return 45
        case .paras:
            return 46
        case .parasect:
            return 47
        case .venonat:
            return 48
        case .venomoth:
            return 49
        case .diglett:
            return 50
        case .dugtrio:
            return 51
        case .meowth:
            return 52
        case .persian:
            return 53
        case .psyduck:
            return 54
        case .golduck:
            return 55
        case .mankey:
            return 56
        case .primeape:
            return 57
        case .growlithe:
            return 58
        case .arcanine:
            return 59
        case .poliwag:
            return 60
        case .poliwhirl:
            return 61
        case .poliwrath:
            return 62
        case .abra:
            return 63
        case .kadabra:
            return 64
        case .alakazam:
            return 65
        case .machop:
            return 66
        case .machoke:
            return 67
        case .machamp:
            return 68
        case .bellsprout:
            return 69
        case .weepinbell:
            return 70
        case .victreebel:
            return 71
        case .tentacool:
            return 72
        case .tentacruel:
            return 73
        case .geodude:
            return 74
        case .graveler:
            return 75
        case .golem:
            return 76
        case .ponyta:
            return 77
        case .rapidash:
            return 78
        case .slowpoke:
            return 79
        case .slowbro:
            return 80
        case .magnemite:
            return 81
        case .magneton:
            return 82
        case .farfetchd:
            return 83
        case .doduo:
            return 84
        case .dodrio:
            return 85
        case .seel:
            return 86
        case .dewgong:
            return 87
        case .grimer:
            return 88
        case .muk:
            return 89
        case .shellder:
            return 90
        case .cloyster:
            return 91
        case .gastly:
            return 92
        case .haunter:
            return 93
        case .gengar:
            return 94
        case .onix:
            return 95
        case .drowzee:
            return 96
        case .hypno:
            return 97
        case .krabby:
            return 98
        case .kingler:
            return 99
        case .voltorb:
            return 100
        case .electrode:
            return 101
        case .exeggcute:
            return 102
        case .exeggutor:
            return 103
        case .cubone:
            return 104
        case .marowak:
            return 105
        case .hitmonlee:
            return 106
        case .hitmonchan:
            return 107
        case .lickitung:
            return 108
        case .koffing:
            return 109
        case .weezing:
            return 110
        case .rhyhorn:
            return 111
        case .rhydon:
            return 112
        case .chansey:
            return 113
        case .tangela:
            return 114
        case .kangaskhan:
            return 115
        case .horsea:
            return 116
        case .seadra:
            return 117
        case .goldeen:
            return 118
        case .seaking:
            return 119
        case .staryu:
            return 120
        case .starmie:
            return 121
        case .mrmime:
            return 122
        case .scyther:
            return 123
        case .jynx:
            return 124
        case .electabuzz:
            return 125
        case .magmar:
            return 126
        case .pinsir:
            return 127
        case .tauros:
            return 128
        case .magikarp:
            return 129
        case .gyarados:
            return 130
        case .lapras:
            return 131
        case .ditto:
            return 132
        case .eevee:
            return 133
        case .vaporeon:
            return 134
        case .jolteon:
            return 135
        case .flareon:
            return 136
        case .porygon:
            return 137
        case .omanyte:
            return 138
        case .omastar:
            return 139
        case .kabuto:
            return 140
        case .kabutops:
            return 141
        case .aerodactyl:
            return 142
        case .snorlax:
            return 143
        case .articuno:
            return 144
        case .zapdos:
            return 145
        case .moltres:
            return 146
        case .dratini:
            return 147
        case .dragonair:
            return 148
        case .dragonite:
            return 149
        case .mewtwo:
            return 150
        case .mew:
            return 151
        }
    }
}
